---
- hosts: all 
  become: yes

  vars:
    jeknins_url_username: admin
    jenkins_url_password: admin

  pre_tasks:
  - name: Update packages
    apt:
      update_cache: yes
      upgrade: dist
  - name: Install java v8
    apt:
      name: openjdk-8-jdk
      state: latest 

  roles: 
    - role: jenkins-setup 
